In [153]:
import os
import pandas as pd
root = 'C:/Users/lenovo/Desktop/Clinical_HL7_Samples'

In [154]:
folder1 = 'C:/Users/lenovo/Desktop/Clinical_HL7_Samples/ELR-ExampleMessages-1.9.2-012216/Elr-ExampleMessages-1.9.2-012216'
folder2 = 'C:/Users/lenovo/Desktop/Clinical_HL7_Samples/Immunization-ExampleMessages-1.9-021214'
folder3 = 'C:/Users/lenovo/Desktop/Clinical_HL7_Samples/Older'
folder4 = 'C:/Users/lenovo/Desktop/Clinical_HL7_Samples/Syndromic-ExampleMessages-1.6-081313/Syndromic-ExampleMessages-1.6-081313'

In [157]:
lst = []
folders = [folder1, folder2, folder3,folder4]
for n in folders:
    for root,d_names,f_names in os.walk(n):
        for i in f_names:
            with open(n+'/'+i, 'r') as f:
                for seg in f:
                    if seg.startswith('PID')==True:
                        fields = seg.split('|')
                        lst.append(fields)

df = pd.DataFrame(lst)

In [158]:
df

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,PID,1,,18547545^^^NIST MPI&2.16.840.1.113883.3.72.5.3...,,Lerr^Todd^G.^Jr^^^L~Gwinn^Theodore^F^Jr^^^B,Doolittle^Ramona^G.^Jr^Dr^^M^^^^^^^PhD,20090607,M,,...,,,,,N,,,201206170000-0500,University H^2.16.840.1.113883.3.0^ISO,337915000^Homo sapiens (organism)^SCT^human^hu...
1,PID,1,,18568545^^^NIST MPI&2.16.840.1.113883.3.72.5.3...,,HepBee^Harry^G.^Jr^^^L~Ryu^Jae^Kuk^Jr^^^B,HepBee^Lee^G.^Sr^Dr^^M^^^^^^^PhD,20000801,M,,...,,,,,N,,,201208060000-0500,Sick Kids Hosp^2.16.840.1.113883.3.0^ISO,337915000^Homo sapiens (organism)^SCT^human^hu...
2,PID,1,,18789547^^^NIST MPI&2.16.840.1.113883.3.72.5.3...,,Sanchez^Abel^G.^Jr^^^L~Caliez^Luis^Munoz^Jr^^^B,Sanchez^Rose^G.^Sr^Dr^^M^^^^^^^CPA,19800320,M,,...,,,,,N,,,201208021600-0500,Shady Tree^2.16.840.1.113883.3.0^ISO,337915000^Homo sapiens (organism)^SCT^human^hu...
3,PID,1,,12346^^^NIST MPI&2.16.840.1.113883.3.72.5.30.2...,,Diode^Maria^^^^^L,,19660130,F,,...,None,None,None,None,None,None,None,None,None,None
4,PID,1,,12346^^^NIST MPI&2.16.840.1.113883.3.72.5.30.2...,,Caddis^Carol^^^^^L,,19851113,F,,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,PID,1,,33333^^^^MR,,^^^^^^~^^^^^^S,,,F,,...,None,None,None,None,None,None,None,None,None,None
373,PID,1,,33333^^^^MR,,^^^^^^~^^^^^^S,,,M,,...,None,None,None,None,None,None,None,None,None,None
374,PID,1,,3333^^^^MR,,^^^^^^~^^^^^^S,,,M,,...,None,None,None,None,None,None,None,None,None,None
375,PID,1,,33333^^^^MR,,^^^^^^~^^^^^^S,,,F,,...,None,None,None,None,None,None,None,None,None,None
376,PID,1,,33333^^^^MR,,^^^^^^~^^^^^^S,,,M,,...,None,None,None,None,None,None,None,None,None,None

## In what year was the youngest male patient born?

In [159]:
df_male = df.loc[df.iloc[:, 8]=='M']
df_male_2 = df.loc[df.iloc[:, 8]=='M\n']
max(df_male.iloc[:, 7].max(), df_male_2.iloc[:,7].max())

'20120325'

### Answer - 2012

## How many unique female patients do we have in this dataset?

In [160]:
df_female = df.loc[df.iloc[:, 8].isin(['F','F\n'])]
df_female.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
3,PID,1,,12346^^^NIST MPI&2.16.840.1.113883.3.72.5.30.2...,,Diode^Maria^^^^^L,,19660130,F,,...,None,None,None,None,None,None,None,None,None,None
4,PID,1,,12346^^^NIST MPI&2.16.840.1.113883.3.72.5.30.2...,,Caddis^Carol^^^^^L,,19851113,F,,...,None,None,None,None,None,None,None,None,None,None
5,PID,1,,12346^^^NIST MPI&2.16.840.1.113883.3.72.5.30.2...,,Parmanti^Sandy^^^^^L,,19900401,F,,...,None,None,None,None,None,None,None,None,None,None
7,PID,1,,PATID123487^^^&2.16.840.1.113883.3.17.5.54&ISO^MR,,Kamehameha^Lahela^^^^^L,,19910615,F,,...,None,None,None,None,None,None,None,None,None,None
12,PID,1,,PATID1234^^^MPI&2.16.840.1.113883.3.0.0.0.3&IS...,,Smirnoff^Peggy^^^^^L,,19750401,F,,...,None,None,None,None,None,None,None,None,None,None

In [161]:
len(Counter(df_female.iloc[:, 5]))

146

### Answer - 146